# Generated by Django 4.0.4 on 2022-04-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=32)),
                ('Category', models.CharField(max_length=32)),
                ('Breed', models.CharField(max_length=32)),
                ('Description', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=2000)),
            ],
        ),
    ]
