# Generated by Django 4.0.4 on 2022-04-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_api', '0002_rename_description_post_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
