# Generated by Django 4.0.4 on 2022-04-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_api', '0003_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
