# Generated by Django 4.0.4 on 2022-04-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_api', '0003_alter_post_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
