# Generated by Django 4.0.4 on 2022-04-27 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_api', '0004_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='img',
        ),
    ]
