# Generated by Django 4.0.4 on 2022-04-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_api', '0004_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
