# Generated by Django 4.0.4 on 2022-04-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_dweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='dweet',
            name='breed',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='dweet',
            name='category',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='dweet',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dweet',
            name='img',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='dweet',
            name='petname',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='dweet',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
